INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'-1', N'root', NULL)
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'0', N'consequat metus', N'-1')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'1', N'Morbi', N'0')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'2', N'volutpat', N'-1')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'3', N'condimentum', N'-1')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'4', N'Lorem', N'1')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'5', N'Goldenrod', N'2')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'6', N'felis', N'3')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'7', N'suscipit', N'1')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'8', N'quis odio', N'7')
INSERT INTO [dbo].[Category] ([Id], [Title], [Parent]) VALUES (N'9', N'posuere', N'6')
