//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AztechService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Vendor : global::System.Configuration.ApplicationSettingsBase {
        
        private static Vendor defaultInstance = ((Vendor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Vendor())));
        
        public static Vendor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=D:\\data\\db\\verdana.mdf;Integr" +
            "ated Security=True;Connect Timeout=30")]
        public string ConnString {
            get {
                return ((string)(this["ConnString"]));
            }
        }
    }
}
